package de.uni_leipzig.simba.memorymanagement.structure;

public enum ParameterType {

	ROLE,DATA,CACHE,CAPACITY,CLUSTER,SOLVERPARAMETER,OPTIMTIME,SOLVER,ITERATIONS,THRESHOLDS,PART,REPEATS,TYPE,CORE,BASEFOLDER,RESULTSFOLDER,INFOFOLDER,RECORDRUNTIMES
}
